### ISSUE TITLE
Search Screen

### ISSUE THREAD

**Issue by mpnouwens** [mpnouwens/vidnation#2]
- As a user I can enter text into the text field
- As a user I am able to select a filter
- Receive response from API

Components:
 - Search bar input (component)
- Build out filter functionality (component)

Tests:
- Add unit tests to components

API: 
- Using OMDb API

**Comment by cos1715** [comment]
Can u provide a description for a problem?

**Comment by mpnouwens** [comment]
> Can u provide a description for a problem?

I will add descriptions to these cards going forward 💯
